/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  CheckCircle2, 
  XCircle, 
  RefreshCcw, 
  Info, 
  GripVertical, 
  Database, 
  Layers, 
  Zap, 
  BarChart3, 
  ShieldCheck,
  ArrowRight,
  Plus,
  Target,
  BookOpen
} from 'lucide-react';
import {
  DndContext,
  useDraggable,
  useDroppable,
  DragOverlay,
  defaultDropAnimationSideEffects,
  type DropAnimation,
  PointerSensor,
  useSensor,
  useSensors,
} from '@dnd-kit/core';
import { CSS } from '@dnd-kit/utilities';

// Types
type SlotId = 1 | 2 | 3 | 4 | 5 | 6;

interface DraggableItem {
  id: string;
  label: string;
  correctSlot: SlotId;
  icon: React.ReactNode;
  description: string;
  details: string[];
}

const ITEMS: DraggableItem[] = [
  { 
    id: 'sources', 
    label: 'Data Sources', 
    correctSlot: 1, 
    icon: <Database size={14} />,
    description: "The origin of all information in the pipeline.",
    details: ["Operational Databases", "SaaS Applications", "Log Files", "IoT Sensors"]
  },
  { 
    id: 'integration', 
    label: 'Data Integration', 
    correctSlot: 2, 
    icon: <Layers size={14} />,
    description: "The process of moving data from sources to storage.",
    details: ["Batch ETL/ELT", "Real-time Streaming", "Change Data Capture (CDC)"]
  },
  { 
    id: 'storage', 
    label: 'Data Storage', 
    correctSlot: 3, 
    icon: <Database size={14} />,
    description: "The central repository where data is kept for analysis.",
    details: ["Cloud Data Warehouses", "Data Lakes", "Object Storage"]
  },
  { 
    id: 'transformation', 
    label: 'Data Transformation', 
    correctSlot: 4, 
    icon: <Zap size={14} />,
    description: "Cleaning, modeling, and preparing data for end-users.",
    details: ["SQL Modeling", "Data Normalization", "Metric Definitions"]
  },
  { 
    id: 'consumers', 
    label: 'Data Consumers', 
    correctSlot: 5, 
    icon: <BarChart3 size={14} />,
    description: "The end-users and systems that derive value from the data.",
    details: ["BI Dashboards", "ML Models", "Operational Apps"]
  },
  { 
    id: 'governance', 
    label: 'Data Governance', 
    correctSlot: 6, 
    icon: <ShieldCheck size={14} />,
    description: "Ensuring data is secure, private, and high quality.",
    details: ["Data Cataloging", "Access Control", "Quality Monitoring"]
  },
];

// Concept Explanations for Tooltips
const CONCEPT_EXPLANATIONS: Record<string, string> = {
  "Entry Point": "The initial stage where data from various external systems enters the pipeline architecture.",
  "Ingestion Layer": "The mechanism used to transport data from source systems into the data storage layer.",
  "Central Repository": "A unified storage system where data is collected, organized, and stored for long-term use.",
  "Compute Engine": "The processing power used to transform, aggregate, and analyze data at scale.",
  "Output Layer": "The final stage where processed data is delivered to end-users and downstream applications.",
  "Cross-Cutting Layer": "Foundational services like security and governance that apply across the entire pipeline.",
  "Applications": "Operational software systems (like CRM or ERP) that generate business data.",
  "API Endpoints": "Web services that provide data in real-time through programmatic requests.",
  "Production DB": "The primary databases used by live applications to store current state.",
  "Event Streams": "Continuous flows of data generated by user actions or system logs (e.g., Kafka).",
  "Legacy Files": "Static data stored in traditional formats like CSV, Excel, or XML.",
  "Cloud Data Warehouse": "A highly scalable database optimized for analytical queries and business intelligence.",
  "Object Storage (Lake)": "A repository for storing vast amounts of raw data in its native format.",
  "BI Dashboards": "Visual tools that provide insights into business performance through charts and metrics.",
  "Predictive Models": "Machine learning algorithms that use historical data to forecast future outcomes.",
  "Customer Data Apps": "Tools that use pipeline data to personalize user experiences or marketing.",
  "Reverse ETL": "The process of moving transformed data from a warehouse back into operational tools.",
  "Data APIs": "Programmatic interfaces that allow external systems to query processed data.",
  "Catalog": "A centralized inventory of all data assets, including metadata and lineage.",
  "Quality": "Automated checks to ensure data is accurate, complete, and reliable.",
  "Privacy": "Controls to protect sensitive information and comply with regulations like GDPR.",
  "Access": "Security mechanisms that manage who can view or modify specific data sets.",
};

function Tooltip({ text, children }: { text: string; children: React.ReactNode }) {
  const [isVisible, setIsVisible] = useState(false);

  return (
    <div className="relative inline-block" onMouseEnter={() => setIsVisible(true)} onMouseLeave={() => setIsVisible(false)}>
      {children}
      <AnimatePresence>
        {isVisible && (
          <motion.div
            initial={{ opacity: 0, y: 5, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 5, scale: 0.95 }}
            className="absolute z-50 bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-2 bg-[#1D1D1D] text-white text-[10px] rounded-lg shadow-xl pointer-events-none"
          >
            {text}
            <div className="absolute top-full left-1/2 -translate-x-1/2 border-8 border-transparent border-t-[#1D1D1D]" />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// Droppable Slot Component
function Slot({ 
  id, 
  item, 
  onRemove, 
  onSelect,
  isWrong, 
  label,
  className = "" 
}: { 
  id: SlotId; 
  item: DraggableItem | null; 
  onRemove: (id: SlotId) => void;
  onSelect: (item: DraggableItem) => void;
  isWrong?: boolean;
  label?: string;
  className?: string;
}) {
  const { isOver, setNodeRef } = useDroppable({
    id: `slot-${id}`,
  });

  return (
    <div className="flex flex-col gap-1.5 w-full">
      {label && (
        <Tooltip text={CONCEPT_EXPLANATIONS[label] || ""}>
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest ml-1 cursor-help border-b border-dotted border-slate-300">
            {label}
          </span>
        </Tooltip>
      )}
      <div 
        ref={setNodeRef}
        className={`relative flex items-center justify-center min-h-[52px] rounded-xl transition-all duration-300 group ${
          isOver ? 'ring-2 ring-brand/50 bg-brand/5' : 'border-slate-200'
        } ${
          item 
            ? isWrong 
              ? 'bg-rose-50 border-rose-200 text-rose-700 shadow-sm' 
              : 'bg-white border-slate-200 text-[#1D1D1D] shadow-sm' 
            : 'bg-slate-50/50 border-2 border-dashed border-slate-200 text-slate-400'
        } border ${className}`}
        onClick={() => {
          if (item) onSelect(item);
        }}
      >
        {item ? (
          <div className="flex items-center justify-between w-full px-4">
            <div className="flex items-center gap-2.5">
              <div className={`p-1.5 rounded-lg ${isWrong ? 'bg-rose-100 text-rose-600' : 'bg-slate-100 text-slate-600'}`}>
                {item.icon}
              </div>
              <span className="text-sm font-semibold tracking-tight">{item.label}</span>
            </div>
            <button 
              className="opacity-0 group-hover:opacity-100 p-1 hover:bg-slate-100 rounded-md transition-all text-slate-400 hover:text-slate-600"
              onClick={() => onRemove(id)}
            >
              <XCircle size={16} />
            </button>
          </div>
        ) : (
          <div className="flex items-center gap-2 opacity-40">
            <Plus size={14} />
            <span className="text-xs font-medium tracking-wide">Drop Component</span>
          </div>
        )}
      </div>
    </div>
  );
}

// Draggable Item Component
function Draggable({ item, onSelect }: { item: DraggableItem; onSelect: (item: DraggableItem) => void }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({
    id: item.id,
    data: item,
  });

  const style = {
    transform: CSS.Translate.toString(transform),
    opacity: isDragging ? 0.3 : 1,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      {...listeners}
      {...attributes}
      onMouseEnter={() => onSelect(item)}
      className="bg-white border border-slate-200 text-[#1D1D1D] px-5 py-3.5 rounded-xl font-semibold text-sm shadow-sm hover:shadow-md hover:border-brand/30 active:scale-95 transition-all cursor-grab active:cursor-grabbing flex items-center gap-3 group"
    >
      <div className="p-1.5 rounded-lg bg-slate-50 text-slate-400 group-hover:bg-brand/10 group-hover:text-brand transition-colors">
        {item.icon}
      </div>
      {item.label}
      <GripVertical size={14} className="ml-auto text-slate-300" />
    </div>
  );
}

const dropAnimation: DropAnimation = {
  sideEffects: defaultDropAnimationSideEffects({
    styles: {
      active: {
        opacity: '0.5',
      },
    },
  }),
};

export default function App() {
  const [placedItems, setPlacedItems] = useState<Record<SlotId, DraggableItem | null>>({
    1: null, 2: null, 3: null, 4: null, 5: null, 6: null
  });
  const [availableItems, setAvailableItems] = useState<DraggableItem[]>(() => 
    [...ITEMS].sort(() => Math.random() - 0.5)
  );
  const [activeId, setActiveId] = useState<string | null>(null);
  const [lastPlacedItem, setLastPlacedItem] = useState<DraggableItem | null>(null);
  const [checked, setChecked] = useState(false);
  const [isGameComplete, setIsGameComplete] = useState(false);

  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: {
        distance: 8,
      },
    })
  );

  const activeItem = useMemo(
    () => ITEMS.find((item) => item.id === activeId),
    [activeId]
  );

  const handleDragStart = (event: any) => {
    setActiveId(event.active.id);
    setChecked(false);
  };

  const handleDragEnd = (event: any) => {
    const { active, over } = event;
    setActiveId(null);

    if (over && over.id.startsWith('slot-')) {
      const slotId = parseInt(over.id.replace('slot-', '')) as SlotId;
      const item = active.data.current as DraggableItem;

      const existingItem = placedItems[slotId];
      
      setPlacedItems(prev => ({ ...prev, [slotId]: item }));
      setLastPlacedItem(item);
      setAvailableItems(prev => {
        const filtered = prev.filter(i => i.id !== item.id);
        return existingItem ? [...filtered, existingItem] : filtered;
      });
    }
  };

  const removeItem = (slotId: SlotId) => {
    const item = placedItems[slotId];
    if (item) {
      setAvailableItems(prev => [...prev, item]);
      setPlacedItems(prev => ({ ...prev, [slotId]: null }));
      setChecked(false);
    }
  };

  const checkAnswers = () => {
    const allPlaced = Object.values(placedItems).every(item => item !== null);
    if (!allPlaced) {
      alert("Please place all components before validating your architecture.");
      return;
    }

    const correctCount = Object.entries(placedItems).filter(([slotId, item]) => {
      return (item as DraggableItem)?.correctSlot === parseInt(slotId);
    }).length;

    const isAllCorrect = correctCount === ITEMS.length;
    setChecked(true);
    
    if (isAllCorrect) {
      setIsGameComplete(true);
    }
  };

  const resetGame = () => {
    setPlacedItems({ 1: null, 2: null, 3: null, 4: null, 5: null, 6: null });
    setAvailableItems([...ITEMS].sort(() => Math.random() - 0.5));
    setChecked(false);
    setIsGameComplete(false);
  };

  return (
    <DndContext 
      sensors={sensors}
      onDragStart={handleDragStart}
      onDragEnd={handleDragEnd}
    >
      <div className="min-h-screen blueprint-grid flex flex-col items-center py-12 px-4 selection:bg-brand/10">
        <div className="max-w-6xl w-full space-y-10">
          
          {/* Header Section */}
          <div className="space-y-8">
            <div className="text-center space-y-3">
              <h1 className="text-4xl md:text-5xl font-black text-[#1D1D1D] tracking-tight">
                Data Pipeline <span className="text-brand">Architect</span>
              </h1>
              <p className="text-slate-500 max-w-xl mx-auto font-medium text-sm md:text-base">
                Design a robust modern data stack by placing the architectural components in their correct sequence.
              </p>
            </div>

            {/* Exercise Brief */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm">
                <h2 className="text-sm font-bold text-brand uppercase tracking-widest mb-3 flex items-center gap-2">
                  <Target size={16} /> Objective
                </h2>
                <p className="text-sm text-slate-600 leading-relaxed">
                  Construct a functional end-to-end data pipeline. Your goal is to understand how data flows from raw sources to business value, ensuring every layer is correctly positioned for scalability and governance.
                </p>
              </div>
              <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm">
                <h2 className="text-sm font-bold text-brand uppercase tracking-widest mb-3 flex items-center gap-2">
                  <BookOpen size={16} /> Instructions
                </h2>
                <ul className="text-sm text-slate-600 space-y-2">
                  <li className="flex items-start gap-2">
                    <span className="font-bold text-brand">1.</span> Drag modules from the "Available" pool into the schematic slots.
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="font-bold text-brand">2.</span> Hover over terms to learn about specific data engineering concepts.
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="font-bold text-brand">3.</span> Once all slots are filled, click "Validate Architecture" to check your design.
                  </li>
                </ul>
              </div>
            </div>

            {/* Component Selection Area */}
            <div className="space-y-6">
              <div className="flex items-center justify-between px-2">
                <h3 className="text-lg font-bold text-[#1D1D1D]">Available Modules</h3>
                <div className="flex items-center gap-2 text-xs text-slate-400 font-medium">
                  <Info size={14} />
                  Drag and drop to build your stack
                </div>
              </div>
              
              <div className="bg-slate-100/50 rounded-[32px] p-8 border border-slate-200/50">
                {isGameComplete ? (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="flex flex-col items-center text-center py-4"
                  >
                    <div className="inline-flex p-3 rounded-2xl bg-emerald-50 text-emerald-600 mb-4">
                      <CheckCircle2 size={32} />
                    </div>
                    <h3 className="text-2xl font-black text-[#1D1D1D] mb-2">Architecture Verified</h3>
                    <p className="text-slate-500 mb-8 font-medium text-sm">Your data pipeline design follows industry best practices.</p>
                    <button
                      onClick={resetGame}
                      className="flex items-center gap-2 mx-auto bg-[#1D1D1D] text-white px-8 py-3 rounded-xl font-bold hover:bg-black transition-all active:scale-95"
                    >
                      <RefreshCcw size={18} /> New Design
                    </button>
                  </motion.div>
                ) : (
                  <>
                    <div className="flex flex-wrap justify-center gap-4 min-h-[80px]">
                      <AnimatePresence mode="popLayout">
                        {availableItems.map((item) => (
                          <motion.div
                            key={item.id}
                            layout
                            initial={{ opacity: 0, scale: 0.8 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={{ opacity: 0, scale: 0.5 }}
                          >
                            <Draggable item={item} onSelect={setLastPlacedItem} />
                          </motion.div>
                        ))}
                      </AnimatePresence>
                    </div>

                    {availableItems.length === 0 && (
                      <motion.div
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="mt-10 flex justify-center"
                      >
                        <button
                          onClick={checkAnswers}
                          className="bg-brand text-white px-10 py-4 rounded-2xl font-bold text-sm uppercase tracking-widest hover:bg-brand-dark transition-all shadow-lg shadow-brand/20 hover:shadow-xl active:scale-95"
                        >
                          Validate Architecture
                        </button>
                      </motion.div>
                    )}
                  </>
                )}
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            {/* Main Schematic Area */}
            <div className="lg:col-span-3 glass-panel rounded-[32px] p-8 md:p-12 relative">
            {/* Background decorative elements */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-brand/5 rounded-full blur-3xl -mr-32 -mt-32 opacity-50" />
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-slate-100 rounded-full blur-3xl -ml-32 -mb-32 opacity-50" />

            <div className="relative grid grid-cols-1 md:grid-cols-3 gap-x-16 gap-y-12">
              
              {/* Column 1: Sources */}
              <div className="space-y-6">
                <Slot 
                  id={1} 
                  label="Entry Point"
                  item={placedItems[1]} 
                  onRemove={removeItem} 
                  onSelect={setLastPlacedItem}
                  isWrong={checked && placedItems[1]?.correctSlot !== 1}
                />
                <div className="bg-slate-50/80 rounded-2xl p-6 border border-slate-200/60 space-y-4">
                  <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider">
                    <Database size={14} />
                    Raw Inputs
                  </div>
                  <ul className="space-y-2.5">
                    {['Applications', 'API Endpoints', 'Production DB', 'Event Streams', 'Legacy Files'].map(text => (
                      <li key={text} className="flex items-center gap-3 text-sm font-medium text-slate-600">
                        <div className="w-1 h-1 rounded-full bg-slate-300" />
                        <Tooltip text={CONCEPT_EXPLANATIONS[text] || ""}>
                          <span className="cursor-help border-b border-dotted border-slate-200">{text}</span>
                        </Tooltip>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Column 2: Processing & Storage */}
              <div className="space-y-8 relative">
                {/* Connector Arrows (Desktop) */}
                <div className="hidden md:block absolute -left-12 top-1/2 -translate-y-1/2 text-slate-300">
                  <ArrowRight size={24} />
                </div>
                <div className="hidden md:block absolute -right-12 top-1/2 -translate-y-1/2 text-slate-300">
                  <ArrowRight size={24} />
                </div>

                <div className="space-y-6">
                  <Slot 
                    id={2} 
                    label="Ingestion Layer"
                    item={placedItems[2]} 
                    onRemove={removeItem} 
                    onSelect={setLastPlacedItem}
                    isWrong={checked && placedItems[2]?.correctSlot !== 2}
                  />
                  
                  <div className="relative py-4">
                    <div className="absolute inset-0 flex items-center justify-center">
                      <div className="w-px h-full bg-slate-200" />
                    </div>
                    <div className="relative z-10 flex justify-center">
                      <div className="bg-white px-3 py-1 rounded-full border border-slate-200 text-[10px] font-bold text-slate-400 uppercase tracking-widest">Flow</div>
                    </div>
                  </div>

                  <Slot 
                    id={3} 
                    label="Central Repository"
                    item={placedItems[3]} 
                    onRemove={removeItem} 
                    onSelect={setLastPlacedItem}
                    isWrong={checked && placedItems[3]?.correctSlot !== 3}
                  />
                  
                  <div className="bg-slate-50/80 rounded-2xl p-5 border border-slate-200/60">
                    <ul className="space-y-2">
                      <li className="flex items-center gap-3 text-sm font-medium text-slate-600">
                        <div className="w-1.5 h-1.5 rounded-full bg-brand" />
                        <Tooltip text={CONCEPT_EXPLANATIONS['Cloud Data Warehouse'] || ""}>
                          <span className="cursor-help border-b border-dotted border-slate-200">Cloud Data Warehouse</span>
                        </Tooltip>
                      </li>
                      <li className="flex items-center gap-3 text-sm font-medium text-slate-600">
                        <div className="w-1.5 h-1.5 rounded-full bg-brand" />
                        <Tooltip text={CONCEPT_EXPLANATIONS['Object Storage (Lake)'] || ""}>
                          <span className="cursor-help border-b border-dotted border-slate-200">Object Storage (Lake)</span>
                        </Tooltip>
                      </li>
                    </ul>
                  </div>

                  <div className="flex flex-col items-center gap-2">
                    <div className="text-slate-300">↕</div>
                    <Slot 
                      id={4} 
                      label="Compute Engine"
                      item={placedItems[4]} 
                      onRemove={removeItem} 
                      onSelect={setLastPlacedItem}
                      isWrong={checked && placedItems[4]?.correctSlot !== 4}
                    />
                  </div>
                </div>
              </div>

              {/* Column 3: Consumption */}
              <div className="space-y-6">
                <Slot 
                  id={5} 
                  label="Output Layer"
                  item={placedItems[5]} 
                  onRemove={removeItem} 
                  onSelect={setLastPlacedItem}
                  isWrong={checked && placedItems[5]?.correctSlot !== 5}
                />
                <div className="bg-slate-50/80 rounded-2xl p-6 border border-slate-200/60 space-y-4">
                  <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider">
                    <BarChart3 size={14} />
                    Value Delivery
                  </div>
                  <ul className="space-y-2.5">
                    {['BI Dashboards', 'Predictive Models', 'Customer Data Apps', 'Reverse ETL', 'Data APIs'].map(text => (
                      <li key={text} className="flex items-center gap-3 text-sm font-medium text-slate-600">
                        <div className="w-1 h-1 rounded-full bg-slate-300" />
                        <Tooltip text={CONCEPT_EXPLANATIONS[text] || ""}>
                          <span className="cursor-help border-b border-dotted border-slate-200">{text}</span>
                        </Tooltip>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            {/* Bottom Governance Bar */}
            <div className="mt-16 pt-8 border-t border-slate-100 flex flex-col md:flex-row items-center gap-8">
              <div className="w-full md:w-1/3">
                <Slot 
                  id={6} 
                  label="Cross-Cutting Layer"
                  item={placedItems[6]} 
                  onRemove={removeItem} 
                  onSelect={setLastPlacedItem}
                  isWrong={checked && placedItems[6]?.correctSlot !== 6}
                />
              </div>
              <div className="flex-1 grid grid-cols-2 md:grid-cols-4 gap-4 w-full">
                {['Catalog', 'Quality', 'Privacy', 'Access'].map(text => (
                  <div key={text}>
                    <Tooltip text={CONCEPT_EXPLANATIONS[text] || ""}>
                      <div className="bg-slate-50 rounded-xl p-3 border border-slate-200/50 text-center cursor-help hover:bg-slate-100 transition-colors">
                        <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">{text}</span>
                      </div>
                    </Tooltip>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Educational Sidebar */}
            <div className="lg:col-span-1 space-y-6">
              <div className="glass-panel rounded-[32px] p-6 h-full flex flex-col">
                <div className="flex items-center gap-2 text-brand mb-4">
                  <Info size={18} />
                  <h3 className="font-bold text-sm uppercase tracking-wider">Architecture Guide</h3>
                </div>
                
                <AnimatePresence mode="wait">
                  {lastPlacedItem ? (
                    <motion.div
                      key={lastPlacedItem.id}
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: -20 }}
                      className="space-y-6"
                    >
                      <div className="space-y-2">
                        <div className="flex items-center gap-2 text-[#1D1D1D]">
                          <div className="p-2 bg-brand/10 rounded-lg text-brand">
                            {lastPlacedItem.icon}
                          </div>
                          <h4 className="font-bold text-lg">{lastPlacedItem.label}</h4>
                        </div>
                        <p className="text-sm text-slate-500 leading-relaxed">
                          {lastPlacedItem.description}
                        </p>
                      </div>

                      <div className="space-y-3">
                        <h5 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Key Concepts</h5>
                        <ul className="space-y-2">
                          {lastPlacedItem.details.map((detail, idx) => (
                            <li key={idx} className="flex items-center gap-2 text-xs font-medium text-slate-600">
                              <div className="w-1 h-1 rounded-full bg-brand" />
                              {detail}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </motion.div>
                  ) : (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="flex-1 flex flex-col items-center justify-center text-center space-y-4 py-12"
                    >
                      <div className="w-12 h-12 rounded-full bg-slate-50 flex items-center justify-center text-slate-300">
                        <Plus size={24} />
                      </div>
                      <p className="text-sm text-slate-400 font-medium px-4">
                        Place a component in the schematic to learn about its role in the pipeline.
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </div>

{checked && !isGameComplete && (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-4 bg-rose-50 border border-rose-100 rounded-2xl text-center flex items-center justify-center gap-3 text-rose-600 text-sm font-bold"
            >
              <XCircle size={18} />
              Validation failed. Review the highlighted components.
            </motion.div>
          )}
        </div>

        {/* Drag Overlay */}
        <DragOverlay dropAnimation={dropAnimation}>
          {activeId ? (
            <div className="bg-white border-2 border-brand text-[#1D1D1D] px-6 py-4 rounded-2xl font-bold text-sm uppercase tracking-widest shadow-2xl flex items-center gap-3 cursor-grabbing scale-105">
              <div className="p-1.5 rounded-lg bg-brand/10 text-brand">
                {activeItem?.icon}
              </div>
              {activeItem?.label}
              <GripVertical size={14} className="ml-auto text-slate-300" />
            </div>
          ) : null}
        </DragOverlay>
      </div>
    </DndContext>
  );
}
